# Generated by Django 5.1 on 2024-09-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True,
                                   verbose_name='Chat-id телеграмма'),
        ),
    ]
