# Generated by Django 5.1 on 2024-08-29 14:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('place',
                 models.CharField(blank=True, max_length=255, null=True,
                                  verbose_name='Место')),
                ('time', models.TimeField(blank=True, null=True,
                                          verbose_name='Время')),
                ('action',
                 models.CharField(blank=True, max_length=255, null=True,
                                  verbose_name='Действие')),
                ('pleasant', models.BooleanField(blank=True, null=True,
                                                 verbose_name='Приятная привычка')),  # noqa
                ('related_habit',
                 models.CharField(blank=True, max_length=255, null=True,
                                  verbose_name='Связанная привычка')),
                ('reward',
                 models.CharField(blank=True, max_length=255, null=True,
                                  verbose_name='Вознаграждение')),
                ('periodicity',
                 models.PositiveIntegerField(blank=True, default=1, null=True,
                                             validators=[
                                                 django.core.validators.MaxValueValidator(  # noqa
                                                     7)],
                                             verbose_name='Периодичность')),
                ('time_to_complete',
                 models.PositiveIntegerField(blank=True, null=True,
                                             validators=[
                                                 django.core.validators.MaxValueValidator(  # noqa
                                                     120)],
                                             verbose_name='Время на выполнение')),  # noqa
                ('sign_of_publicity',
                 models.BooleanField(blank=True, default=False, null=True,
                                     verbose_name='Признак публичности')),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='habit',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
